Website/config/routes.rb
Website::Application.routes.draw do
  root :to => 'appointments#new'

  match '/thanks' => 'pages#thanks'

  resources :services

  resources :users

  resources :appointments

  match 'export_appointment/:id' => 'appointments#export_appointments'

  match '/admin' => 'appointments#index'

end

Website/app/models/appointment.rb
class Appointment < ActiveRecord::Base
  attr_accessible :appot, 
  				  :email, 
  		  	  	  :first_name, 
      		  	  :last_name, 
  				  :message, 
  				  :phone, 
  				  :service_id

  belongs_to :service

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates_format_of :email, 
  					  :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
  validates_format_of :phone, 
   					  :with => /\A\(?(\d{3})[-\)]?\s?(\d{3})[-\s]?(\d{4})\z/

end

Website/app/models/service.rb
class Service < ActiveRecord::Base
  attr_accessible :service_description, :service_time_estimate
  has_many :appointments

  # TODO: validates service time is no greater than 3 hours

  validates_numericality_of :service_time_estimate, :greater_than => 0
  validates_numericality_of :service_time_estimate, :less_than => 181

end

Website/app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :full_name, :password, :username
end

Website/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :login, :except => [:new, :create]
  
  private
  
  def login
    authenticate_or_request_with_http_basic("Appointment Admin") do |username, password|
      user = User.find_by_username(username)
      user != nil && password == user.password
    end
  end
end

Website/app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  # GET /appointments
  # GET /appointments.json
  def index
    @appointments = Appointment.find(:all, :order=>'appot')

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @appointments }
    end
  end

  # GET /appointments/1
  # GET /appointments/1.json
	
  def show
    @appointment = Appointment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @appointment }
    end
  end

  # GET /appointments/new
  # GET /appointments/new.json
  def new
    @appointment = Appointment.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @appointment }
    end
  end

  # GET /appointments/1/edit
  def edit
    @appointment = Appointment.find(params[:id])
  end

  # POST /appointments
  # POST /appointments.json
  def create
    @appointment = Appointment.new(params[:appointment])

    respond_to do |format|
      if @appointment.save
        AppointmentMailer.tap do |mail|
          mail.new_appointment_to_stylist(@appointment).deliver
          mail.new_appointment_to_client(@appointment).deliver
        end
        format.html { redirect_to thanks_url, notice: 'Appointment was successfully created.' }
        format.json { render json: @appointment, status: :created, location: @appointment }
      else
        format.html { render action: "new" }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  #below was if we want to thanks page to list the appointment
  #def thanks
  #  @appointments = Appointment.find(:all, :order=>'appot')

  #  respond_to do |format|
  #    format.html # thanks.html.erb
  #    format.json { render json: @appointments }
  #  end
  #end

  # PUT /appointments/1
  # PUT /appointments/1.json
  def update
    @appointment = Appointment.find(params[:id])

    respond_to do |format|
      if @appointment.update_attributes(params[:appointment])
        format.html { redirect_to @appointment, notice: 'Appointment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /appointments/1
  # DELETE /appointments/1.json
  def destroy
    @appointment = Appointment.find(params[:id])
    @appointment.destroy

    respond_to do |format|
      format.html { redirect_to appointments_url }
      format.json { head :no_content }
    end
  end

end

Website/app/controllers/services_controller.rb
class ServicesController < ApplicationController
  # GET /services
  # GET /services.json
  def index
    @services = Service.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @services }
    end
  end

  # GET /services/1
  # GET /services/1.json
  def show
    @service = Service.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @service }
    end
  end

  # GET /services/new
  # GET /services/new.json
  def new
    @service = Service.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @service }
    end
  end

  # GET /services/1/edit
  def edit
    @service = Service.find(params[:id])
  end

  # POST /services
  # POST /services.json
  def create
    @service = Service.new(params[:service])

    respond_to do |format|
      if @service.save
        format.html { redirect_to @service, notice: 'Service was successfully created.' }
        format.json { render json: @service, status: :created, location: @service }
      else
        format.html { render action: "new" }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /services/1
  # PUT /services/1.json
  def update
    @service = Service.find(params[:id])

    respond_to do |format|
      if @service.update_attributes(params[:service])
        format.html { redirect_to @service, notice: 'Service was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /services/1
  # DELETE /services/1.json
  def destroy
    @service = Service.find(params[:id])
    @service.destroy

    respond_to do |format|
      format.html { redirect_to services_url }
      format.json { head :no_content }
    end
  end
end

Website/app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

Website/app/helpers/application_helper.rb
module ApplicationHelper
end

Website/app/helpers/appointments_helper.rb
module AppointmentsHelper
end

Website/app/helpers/services_helper.rb
module ServicesHelper
end

Website/app/helpers/users_helper.rb
module UsersHelper
end

Website/app/views/appointments/_form.html.erb
<%= form_for(@appointment) do |f| %>
  <% if @appointment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@appointment.errors.count, "error") %> prohibited this appointment from being saved:</h2>

      <ul>
      <% @appointment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :phone %><br />
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <p>Select Date and Time For Your Appointment</p>
    <%= f.datetime_select :appot, :minute_step => 10, ampm: true %>
  </div>
  <div class="field">
    <%= f.label :service_id %><br />
    <%= f.collection_select :service_id, Service.all, :id, :service_description %>
  </div>
  <div class="field">
    <%= f.label :message %><br />
    <%= f.text_area :message %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Website/app/views/appointments/edit.html.erb
<h1>Editing appointment</h1>

<%= render 'form' %>

<%= link_to 'Show', @appointment %> |
<%= link_to 'Back', appointments_path %>

Website/app/views/appointments/index.html.erb
<div class="header-strip">
<h1 >Admin Page</h1>
</div>
<h3>Quick Links</h3>
<p>
<ul>
<li><a href="/services">edit services</a></li>
<li><a href="/users">edit users</a></li>
</p>


<!--<%= link_to 'New Appointment', new_appointment_path %>-->
<div>
<h2> 
Requested Appointments
</h2>
<table>
  <tr>
    <th>First Name</th>
    <th>Last Name</th>
    <th>Phone</th>
    <th>Email</th>
    <th>Date/Time</th>
    <th>Service</th>
    <th>Message</th>
    <th></th>
  </tr>

<% @appointments.each do |appointment| %>
  <tr>
    <td><%= appointment.first_name %></td>
    <td><%= appointment.last_name %></td>
    <td><%= appointment.phone %></td>
    <td><%= appointment.email %></td>
    <td><%= appointment.appot.localtime %></td>
    <td><%= appointment.service.service_description %></td>
    <td><%= appointment.message %></td>
    <td>
        <%= link_to 'Show', appointment %>
        <%= link_to 'Edit', edit_appointment_path(appointment) %>
        <%= link_to 'Destroy', appointment, method: :delete, data: { confirm: 'Are you sure?' } %>
    </td>
  </tr>
<% end %>
</table>
</div>

Website/app/views/appointments/new.html.erb
<div class="header-strip">
	<h1>New appointment</h1>
</div>
<p>Welcome to Alysia's Beauty Shop! </br>
Request an appointment by filling out the form below.
Alysia will get in touch with you to confirm or reschedule your appointment.</p>

<%= render 'form' %>

<!--<%= link_to 'Back', appointments_path %>-->

Website/app/views/appointments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>First Name:</b>
  <%= @appointment.first_name %>
</p>

<p>
  <b>Last Name:</b>
  <%= @appointment.last_name %>
</p>

<p>
  <b>Phone:</b>
  <%= @appointment.phone %>
</p>

<p>
  <b>Email:</b>
  <%= @appointment.email %>
</p>

<p>
  <b>Date/Time:</b>
  <%= @appointment.appot %>
</p>

<p>
  <b>Service:</b>
  <%= @appointment.service.service_description %>
</p>

<p>
  <b>Message:</b>
  <%= @appointment.message %>
</p>


<%= link_to 'Edit', edit_appointment_path(@appointment) %> |
<%= link_to 'Back', appointments_path %>

Website/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Men's Hair Cuts, Women's Hair Cuts, Coloring In Truckee</title> 
  <meta name="description" content="Professional, experienced stylist Alicia offers men's haircuts, women's 
	haircuts and coloring in Truckee.">
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	
<%= yield %>

</body>
</html>

Website/app/views/services/_form.html.erb
<%= form_for(@service) do |f| %>
  <% if @service.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@service.errors.count, "error") %> prohibited this service from being saved:</h2>

      <ul>
      <% @service.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :service_description %><br />
    <%= f.text_field :service_description %>
  </div>
  <div class="field">
    <p>Enter Time In Minutes</p>
    <%= f.label :service_time_estimate %><br />
    <%= f.number_field :service_time_estimate %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Website/app/views/services/edit.html.erb
<h1>Editing service</h1>

<%= render 'form' %>

<%= link_to 'Show', @service %> |
<%= link_to 'Back', services_path %>

Website/app/views/services/index.html.erb
<h1>Listing services</h1>

<p>Below is your services table where you can indicate to your clients which services you offer and the estimated length of time it would take to deliver those services.</p>  

<!--delete "Show" link, change text of "Destroy" link to "Delete", and change text and location of "New Service" to an + symbol to the right of Service Description-->

<table>
  <tr>
    <th>Service description</th>
    <th>Service time estimate</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @services.each do |service| %>
  <tr>
    <td><%= service.service_description %></td>
    <td><%= service.service_time_estimate %></td>
    <td><%= link_to 'Show', service %></td>
    <td><%= link_to 'Edit', edit_service_path(service) %></td>
    <td><%= link_to 'Destroy', service, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Service', new_service_path %> || <a href="/admin">Admin Page</a>

Website/app/views/services/new.html.erb
<h1>New service</h1>

<%= render 'form' %>

<%= link_to 'Back', services_path %>

Website/app/views/services/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Service description:</b>
  <%= @service.service_description %>
</p>

<p>
  <b>Service time estimate:</b>
  <%= @service.service_time_estimate %>
</p>


<%= link_to 'Edit', edit_service_path(@service) %> |
<%= link_to 'Back', services_path %>

Website/app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :full_name %><br />
    <%= f.text_field :full_name %>
  </div>
  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.text_field :password %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Website/app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

Website/app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Full name</th>
    <th>Username</th>
    <th>Password</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.full_name %></td>
    <td><%= user.username %></td>
    <td><%= user.password %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %> || <a href="/admin">Admin Page</a>

Website/app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

Website/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Full name:</b>
  <%= @user.full_name %>
</p>

<p>
  <b>Username:</b>
  <%= @user.username %>
</p>

<p>
  <b>Password:</b>
  <%= @user.password %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>